"""What the engine prints or writes tells its reader to run commands that exist.

WHY A TEST AT ALL. A command written as a Python file run by path prints hints that way:
`python <file>.py`, "re-run <file>.py", a usage line naming the file, a README header
naming the script that generated it. An installed engine has none of those files. It has
one command, `radar <verb>`, so each such hint names something the reader cannot run.
Nothing else in this repository would notice one coming back: the hint is a string, and a
string is never executed by the suite.

WHAT IT READS is the engine's OUTPUT, not its prose: every string constant in the
package's modules except docstrings, and every template `radar init` writes into a
catalogue. A docstring is read with the source open, where the module it describes is
next to it.

IT MATCHES FORMS, NEVER NAMES: a Python file run by `python`, named in a usage line or
told to be run or re-run, and, in the engine's own modules, any path into a `scripts/`
directory. The templates are held to the command forms only, because a template is
written INTO a catalogue, and there `scripts/` is the catalogue's own helper directory -
the marker template seeds the changelog watch with it - so a path under it names the
catalogue's file rather than one the engine lost.

A PACKAGE THAT CANNOT BE READ FAILS rather than passing: no modules or no templates is
exactly what a clean result looks like.
"""

from __future__ import annotations

import ast
import os
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PACKAGE = Path(os.environ.get("RADAR_ENGINE_SRC") or (REPO / "src")) / "stack_radar"

_FILE = r"`?[\w./\\-]*\.py\b"
# A Python file as the thing to run.
_COMMAND = r"\bpython[0-9.]*(?:\.exe)?\s+" + _FILE + r"|\busage:\s+" + _FILE
_COMMAND += r"|\b(?:re-?)?run\s+" + _FILE
# A path into a `scripts/` directory: a command run by path from a source tree, which an
# installed engine does not have.
_SCRIPT_PATH = r"\bscripts/[\w-]+\.py\b"

MODULE_FORMS = re.compile(_COMMAND + "|" + _SCRIPT_PATH)
TEMPLATE_FORMS = re.compile(_COMMAND)


def _docstrings(tree: ast.Module) -> set[int]:
    """The ids of the string constants that are docstrings, which are not output."""
    found = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            body = node.body
            if (
                body
                and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)
            ):
                found.add(id(body[0].value))
    return found


def module_hits(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    docs = _docstrings(tree)
    hits = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str) and id(node) not in docs:
            hits += [
                f"{path.name}:{node.lineno}: {m.group()}" for m in MODULE_FORMS.finditer(node.value)
            ]
    return hits


def template_hits(path: Path) -> list[str]:
    hits = []
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        hits += [
            f"templates/{path.name}:{lineno}: {m.group()}" for m in TEMPLATE_FORMS.finditer(line)
        ]
    return hits


def test_no_printed_or_written_hint_names_a_script_the_engine_does_not_ship():
    modules = sorted(PACKAGE.glob("*.py"))
    templates = sorted(p for p in (PACKAGE / "templates").iterdir() if p.is_file())
    # The guard is only as good as what it read.
    assert any(p.name == "gate.py" for p in modules) and templates, (
        f"no engine modules or no templates under {PACKAGE}, so this guard would read "
        "nothing and pass - which is the wording of a clean scan"
    )
    hits = [h for p in modules for h in module_hits(p)]
    hits += [h for p in templates for h in template_hits(p)]
    assert not hits, (
        f"{len(hits)} printed or written hint(s) name a script the installed engine does "
        "not have - the command is `radar <verb>`: " + "; ".join(hits)
    )


def test_the_forms_match_what_they_are_for():
    # Pinned so a loosened pattern cannot pass the tree by matching nothing.
    for bad in (
        "python scripts/gate.py",
        "then re-run gate.py.",
        "usage: render_feedback_targets.py --env <name>",
        "Generated by `scripts/render.py`",
    ):
        assert MODULE_FORMS.search(bad), bad
    for good in (
        "radar gate",
        "render.py writes `repo` as a link",
        "python -m stack_radar.cli",
        "re-run with --yes",
    ):
        assert not MODULE_FORMS.search(good), good
    assert not TEMPLATE_FORMS.search('# contract_surfaces = ["scripts/your_module.py"]')


# The engine's own documents, which live in its repository and are not in the package.
_ENGINE_DOC = re.compile(r"\b(?:docs/concepts\.md|docs/new-environment\.md|SECURITY\.md)")
REPOSITORY = "https://github.com/grimaldost/stack-radar/"


def _doc_hits(text: str, where: str) -> list[str]:
    """Each mention of an engine document in `text` that is not part of a link into the
    engine's repository."""
    return [
        f"{where}: {m.group()}"
        for m in _ENGINE_DOC.finditer(text)
        if REPOSITORY not in text[max(0, m.start() - 120) : m.start()]
    ]


def test_no_printed_or_written_hint_sends_the_reader_to_a_document_the_package_lacks():
    # An installed engine is the package alone: `docs/` and SECURITY.md stay in the
    # repository, so a hint naming one as a file sends the reader to nothing. It names the
    # page in the repository instead.
    hits = []
    for path in sorted(PACKAGE.glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        docs = _docstrings(tree)
        for node in ast.walk(tree):
            if isinstance(node, ast.Constant) and isinstance(node.value, str):
                if id(node) not in docs:
                    hits += _doc_hits(node.value, f"{path.name}:{node.lineno}")
    for path in sorted(p for p in (PACKAGE / "templates").iterdir() if p.is_file()):
        hits += _doc_hits(path.read_text(encoding="utf-8"), f"templates/{path.name}")
    assert not hits, "; ".join(hits)
