"""Passive field telemetry for a pilot-ring tool, mined post-hoc from transcripts.

Why post-hoc: a pilot must cost nothing to observe. Hooks, prompts, wrappers and
agent cooperation all tax every working session and change the thing being measured.
Claude Code already writes a complete tool-call log to disk, so the honest cheap
option is to read it afterwards. Consequence: this script is retroactive by nature
and adds zero burden — and it can be pointed at a window that predates the decision
to measure.

What the numbers are NOT: causal. There is no control arm here, no counterfactual,
no randomisation. Field telemetry answers "was there ever an opportunity, and did the
tool get used on it" — the opportunity-frequency census that actually decides a
small-effect tool. It cannot answer "did it help". A controlled evaluation answers that.

Reads the data plane (transcripts) read-only and writes only into the radar's own
`field/` directory, so the control-plane invariant holds: nothing is
written into the stack, and the stack is not made aware that the radar exists.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import statistics
import sys
import time
from fnmatch import fnmatch
from pathlib import Path
from typing import NamedTuple

from .bootstrap import home_dir
from .cmdscan import resolve, tokenize
from .paths import field_dir, write_error, write_inside
from .radar_lib import (
    NAME_RULE,
    MATCHER_KEYS,
    begin_command,
    default_environment,
    environment_name,
    is_plain_name,
    load_environment,
    load_tools,
    placeholder_error,
    reports_profile_errors,
)
from .redact import extra_homes, redact_homes, redact_text, scoped_terms
from .render import md_code, md_text

GEN_NOTE = "generated by `radar field` - do not hand-edit"

DESCRIPTIVE_BANNER = (
    "DESCRIPTIVE ONLY - no control arm, no counterfactual, no randomisation. "
    "These counts say whether an opportunity to use the tool ever arose and whether "
    "it was taken. They do NOT say the tool helped, and no number here may be quoted "
    "as an effect size."
)

CHUNK = 1 << 20  # prescan read size; transcripts are streamed, never loaded whole
RAW_CAP = 1000  # per-call audit rows kept in the JSON report
GLOB_META = "*?["
TOOL_USE_ID_RE = re.compile(r'"tool_use_id":"([^"]+)"')
# How far the two independent scanners may disagree before it is worth investigating.
# Not zero: small differences in how the two scanners date or de-duplicate a call are
# expected, and a tolerance of zero would report them as drift.
RECONCILE_TOLERANCE = 0.02


# ------------------------------------------------------------------ matcher plumbing


def literal_prefix(glob: str) -> str:
    """The fixed head of a glob — the part usable as a raw-bytes prescan needle."""
    for i, ch in enumerate(glob):
        if ch in GLOB_META:
            return glob[:i]
    return glob


def matches(name: str, globs: list[str]) -> bool:
    return any(fnmatch(name, g) for g in globs)


def expand_command_globs(globs: list[str]) -> list[str]:
    """The declared command globs, plus the module spelling of each literal one.

    A DISTRIBUTION NAME IS NOT A MODULE NAME, and cmdscan reports the module. It
    resolves `python -m pre_commit` to "pre_commit" because that is what the
    interpreter was told to run, while the radar names the tool the way it is
    installed and published - `pre-commit`. Python packaging turns the hyphen into an
    underscore on import, so an entry written correctly could not match the module
    invocation form.

    That form is not a rarity: where a machine refuses unsigned console-script shims
    (docs/new-environment.md, "Unsigned executables"), `python -m pre_commit` is the only
    way the tool runs, and an entry that matched only the distribution name would report
    a fraction of the real invocations.

    Expanding here rather than adding a second glob to each hyphenated entry: the
    equivalence is a property of Python packaging, not a judgement about one tool, and
    the next hyphenated entry cannot be relied on to remember it. The expansion is inert
    unless the module form is actually invoked.

    Only a LITERAL glob is respelled. In a pattern the hyphen may be structural - in a
    character class it is a range, and `[a-c]` respelled is the set {a, _, c} - so a
    pattern is left exactly as its author wrote it.
    """
    out = list(globs)
    for g in globs:
        if "-" not in g or any(ch in g for ch in GLOB_META):
            continue
        alt = g.replace("-", "_")
        if alt not in out:
            out.append(alt)
    return out


# Tool names that carry a shell command line. Both exist in transcripts.
BASH_TOOLS = ("Bash", "PowerShell")


class Matchers(NamedTuple):
    """One matcher set: the three ways a tool can appear in a transcript.

    Two of these exist per run - the entry's own matchers (did the tool get used) and its
    opportunity matchers (was there an occasion where it would have applied). Bundled
    rather than passed as six positional lists because the scan needs BOTH and a
    nine-argument scan_file was already at the limit of what a reader can hold.
    """

    tool: list[str]  # MCP tool-name globs
    skill: list[str]  # globs over a Skill call's input.skill
    command: list[str]  # globs over a shell command's RESOLVED chain

    def declared(self) -> bool:
        return bool(self.tool or self.skill or self.command)


EMPTY = Matchers([], [], [])


def matched_name(block: dict, name: str, m: Matchers) -> str | None:
    """What this tool_use should be REPORTED as under `m`, or None if it does not match.

    The precedence is deliberate and load-bearing. A skill invocation reaches the
    transcript as tool_use name="Skill" with the skill id in `input.skill`, so an own-ring
    tool - reached through its skills rather than through MCP tools - is only visible by
    matching that field, and it must be reported under the skill id or every own tool
    collapses to the single name "Skill". A CLI reaches it as a Bash/PowerShell call with
    the command line in `input.command`, which is invisible to both other matchers; for
    a stack made mostly of CLIs, telemetry would see almost none of it without this.

    Only Bash calls the AGENT MADE are visible. A CLI the human runs in their own
    terminal, or one wired into a pre-commit hook, never enters a transcript - so a zero
    here means "the agent never reached for it", NOT "it was never used". That is the
    whole reason `also_runs_in` and the opportunity matchers exist.
    """
    if name == "Skill" and m.skill:
        sid = (block.get("input") or {}).get("skill")
        if not isinstance(sid, str) or not matches(sid, m.skill):
            return None
        return f"skill:{sid}"
    if name in BASH_TOOLS and m.command:
        cmd = (block.get("input") or {}).get("command")
        if not isinstance(cmd, str):
            return None
        hit = first_match(cmd, m.command)
        return f"cmd:{hit}" if hit is not None else None
    return name if m.tool and matches(name, m.tool) else None


def matcher_needles(m: Matchers) -> set[str]:
    """The literal heads a raw-byte prescan can look for on behalf of `m`."""
    if not m.declared():
        return set()
    return (
        {literal_prefix(g) for g in m.tool}
        | {literal_prefix(g) for g in m.command}
        | ({'"name":"Skill"'} if m.skill else set())
    )


def command_identities(cmd: str) -> list[str]:
    """Everything a command line can be identified BY: executables, plus script names.

    The executables come from cmdscan.py.
    Splitting a command on newlines and pipes reads heredoc bodies and quoted multi-line
    strings as command lines, and cannot follow a runner chain, which loses real ones.
    Resolving the chain avoids both: `uv run ruff check` counts as BOTH uv and ruff, and
    `python -m pytest` counts as pytest.

    A NOTE ON WHAT THIS CANNOT SEE: `powershell -Command "uv run ruff check ."` resolves
    to ["powershell"] and nothing else - the inner command line is a quoted argument and
    stays opaque, as it is for `bash -c`, `cmd /c`, `python -c` and a heredoc body. That
    is conservative in the safe direction (it never invents an invocation, only loses
    one), so every `cmd:` count is a FLOOR.
    How large a floor depends on how often the agent wraps a command in a shell, which
    varies by machine and shell, so it is left to be measured where it matters rather
    than asserted here. tests/test_cmdscan.py pins the behaviour.

    THE GAP THE CHAIN ALONE LEAVES. cmdscan resolves `uv run python tool.py run` to
    ["uv", "python"], which is correct for its question - what did the shell execute -
    and useless for ours, because a `cli` entry that ships as a python script has no
    other name to be measured under. The interpreter is not the tool.

    So the script filename is added as an identity, and only where it cannot be
    mistaken for a mention: the segment's resolved chain must END at python, i.e. the
    interpreter is what ran the file. `ruff check tool.py`, `git add tool.py` and
    `cat tool.py` all resolve to ruff/git/cat and contribute nothing - which is the
    same substring trap resolving the chain exists to avoid, so it is closed here rather
    than trusted.

    Deliberately NOT pushed down into cmdscan: that module answers what the shell
    executed, the same question an invocation table's `exe` column answers (--reconcile),
    and a script name is the radar's own question. A table that does not record script
    names will therefore report reconcile drift on `command` for an entry matched this
    way. That is a true disagreement, correctly reported; the fix belongs in whatever
    writes that table, not in a fudge here.

    A script identity always carries its `.py`, so a bare executable glob can never
    collide with one.
    """
    out: list[str] = []
    for tokens in tokenize(cmd or ""):
        if not tokens:
            continue
        chain = resolve(tokens)
        for n in chain:
            if n not in out:
                out.append(n)
        if not chain or chain[-1] != "python":
            continue
        for t in tokens:
            if t.startswith("-") or not t.lower().endswith(".py"):
                continue
            base = Path(t.replace("\\", "/")).name
            if base and base not in out:
                out.append(base)
            break
    return out


def first_match(cmd: str, globs: list[str]) -> str | None:
    """The identity that matched, or None. One pass, because the scan is the hot loop.

    Which one matched is what the invocation is reported under - `cmd:ruff` rather than
    a generic `cmd` - so asking twice (does it match / which one) resolved the command
    twice, which is the expensive half.
    """
    return next((h for h in command_identities(cmd) if matches(h, globs)), None)


def prescan_hit(path: Path, needles: list[bytes], overlap: int) -> bool:
    """True if any needle appears in the file's raw bytes.

    A whole-file substring scan is roughly two orders of magnitude cheaper than
    json.loads per line, and the vast majority of transcripts never mention a given
    pilot tool at all. Needles are the globs' literal heads, so this is a superset of
    the real matches with one exception: a chain can resolve through `python` without
    the word in the command line, so run_tool does not prescan for a matcher that
    matches `python`.
    """
    try:
        with path.open("rb") as fh:
            tail = b""
            while True:
                buf = fh.read(CHUNK)
                if not buf:
                    return False
                blob = tail + buf
                for n in needles:
                    if n in blob:
                        return True
                tail = blob[-overlap:] if overlap else b""
    except OSError:
        return False


# --------------------------------------------------------------------------- parsing


def parse_ts(raw: str | None) -> dt.datetime | None:
    if not raw:
        return None
    try:
        # Transcripts write ISO-8601 with a Z suffix; fromisoformat accepts it on 3.11+.
        return dt.datetime.fromisoformat(str(raw))
    except ValueError:
        return None


def iter_blocks(rec: dict):
    msg = rec.get("message")
    if not isinstance(msg, dict):
        return
    content = msg.get("content")
    if not isinstance(content, list):
        return
    for b in content:
        if isinstance(b, dict):
            yield b


class Scan(NamedTuple):
    """One file's yield: what was used, what was replayed, and what the chance was."""

    invocations: list[dict]
    malformed: int
    replayed: list[dict]
    opportunities: list[dict]


def scan_file(
    path: Path,
    session_id: str,
    slug: str,
    subagent: bool,
    use: Matchers,
    text_needles: list[str],
    seen_ids: set[str] | None = None,
    opportunity: Matchers = EMPTY,
    opportunity_seen_ids: set[str] | None = None,
) -> Scan:
    """One streaming pass, answering two questions at once.

    Results are matched back to calls by tool_use_id, which is why the pass keeps a
    pending map: a line that mentions no pilot tool is only parsed when it carries a
    tool_use_id we are actually waiting on.

    REPLAYED HISTORY. Resuming or forking a session writes a NEW transcript that
    replays the earlier one, so the same tool_use id exists in two files. Counting both
    is double-counting one event.
    `seen_ids` carries across files, and callers walk files oldest-first, so the first
    occurrence is the one that counts and the later copies are returned separately
    rather than silently dropped.

    Opportunities get their OWN id set. The two questions are independent, and a call
    that happens to satisfy both matcher sets must count once on each side rather than
    be swallowed by whichever ran first - a shared set would silently make `taken_ratio`
    depend on evaluation order.

    Opportunities carry no latency and no error flag: nothing reads them, and pairing
    each with its tool_result would double the pending map for a number that answers a
    different question. They record only where and when the chance existed.
    """
    invocations: list[dict] = []
    replayed: list[dict] = []
    opportunities: list[dict] = []
    by_id: dict[str, dict] = {}
    seen = seen_ids if seen_ids is not None else set()
    opportunity_seen = opportunity_seen_ids if opportunity_seen_ids is not None else set()
    malformed = 0
    try:
        fh = path.open(encoding="utf-8", errors="replace")
    except OSError:
        return Scan([], 0, [], [])
    with fh:
        for line in fh:
            interesting = any(n in line for n in text_needles)
            if not interesting:
                if not by_id or '"tool_use_id"' not in line:
                    continue
                m = TOOL_USE_ID_RE.search(line)
                if not m or m.group(1) not in by_id:
                    continue
            try:
                rec = json.loads(line)
            except (ValueError, TypeError):
                malformed += 1
                continue
            ts = parse_ts(rec.get("timestamp"))
            for b in iter_blocks(rec):
                btype = b.get("type")
                if btype == "tool_use":
                    raw = b.get("name")
                    if not isinstance(raw, str):
                        continue
                    tid = b.get("id")
                    name = matched_name(b, raw, use)
                    if name is not None:
                        inv = {
                            "tool": name,
                            "at": ts.isoformat() if ts else None,
                            "_ts": ts,
                            "session": session_id,
                            "slug": slug,
                            "subagent": subagent,
                            "latency_ms": None,
                            "is_error": None,
                            "resolved": False,
                        }
                        if isinstance(tid, str) and tid in seen:
                            replayed.append(inv)
                        else:
                            if isinstance(tid, str):
                                seen.add(tid)
                                by_id[tid] = inv
                            invocations.append(inv)
                    chance = matched_name(b, raw, opportunity)
                    if chance is not None and not (
                        isinstance(tid, str) and tid in opportunity_seen
                    ):
                        if isinstance(tid, str):
                            opportunity_seen.add(tid)
                        opportunities.append(
                            {
                                "tool": chance,
                                "at": ts.isoformat() if ts else None,
                                "_ts": ts,
                                "session": session_id,
                                "slug": slug,
                                "subagent": subagent,
                            }
                        )
                elif btype == "tool_result":
                    inv = by_id.pop(b.get("tool_use_id"), None)  # type: ignore[arg-type]
                    if inv is None:
                        continue
                    inv["resolved"] = True
                    inv["is_error"] = bool(b.get("is_error"))
                    if ts and inv["_ts"]:
                        delta = (ts - inv["_ts"]).total_seconds() * 1000.0
                        if delta >= 0:
                            inv["latency_ms"] = round(delta, 1)
    return Scan(invocations, malformed, replayed, opportunities)


def discover(projects: Path) -> list[tuple[Path, str, str, bool]]:
    """(path, session_id, slug, is_subagent) for every transcript on disk."""
    out: list[tuple[Path, str, str, bool]] = []
    if not projects.is_dir():
        return out
    for slug_dir in sorted(p for p in projects.iterdir() if p.is_dir()):
        slug = slug_dir.name
        for f in slug_dir.rglob("*.jsonl"):
            rel = f.relative_to(slug_dir).parts
            if len(rel) == 1:
                out.append((f, f.stem, slug, False))
            else:
                # Sidechain transcripts live under the parent session's uuid directory
                # at varying depth (<uuid>/subagents/..., and .../workflows/wf_*/...),
                # so the invocation is attributed to the parent session rather than
                # counted as a session of its own.
                out.append((f, rel[0], slug, True))
    return out


# ------------------------------------------------------------------ transcripts on disk

# A transcript's own clock. Records are appended in order, so the first timestamp in the
# head and the last in the tail bound the session without parsing the middle.
TS_RE = re.compile(r'"timestamp"\s*:\s*"([^"]+)"')
EDGE = 1 << 16  # bytes read from each end when bounding a transcript in time


def _decode(buf: bytes) -> str:
    return buf.decode("utf-8", errors="replace")


def head_clock(path: Path) -> tuple[dt.datetime | None, dt.datetime | None]:
    """(the FIRST record's timestamp, the EARLIEST timestamp) from one bounded head read.

    They are not the same, and reading them as one puts the retention horizon too late.
    Records are appended in order, so the first timestamp is where the session began -
    which is what the census wants, because that is the session's own clock. But a
    resumed or forked session REPLAYS the session it continues, and the replayed records keep
    their original, earlier timestamps while sitting after the resume header. So the
    earliest timestamp in the file can predate the first one.

    The second element is the earliest timestamp in the head: it costs nothing (the
    bytes are already read) and it reaches back through any replay that fits in the
    head. It is still a bounded read, so it is a CEILING on how far back the evidence
    goes rather than the edge itself - a replay deeper than 64 KiB into a file is not
    seen - and both the finding and the JSON field name say so rather than implying a
    measurement.
    """
    try:
        with path.open("rb") as fh:
            found = TS_RE.findall(_decode(fh.read(EDGE)))
    except OSError:
        return None, None
    if not found:
        return None, None
    stamps = [ts for ts in (parse_ts(s) for s in found) if ts is not None]
    return (parse_ts(found[0]), min(stamps) if stamps else None)


def last_timestamp(path: Path) -> dt.datetime | None:
    """The latest record's timestamp, from a bounded read of the file's tail.

    Bounded on purpose: a transcript can grow large, and the census has to stay cheap
    enough to run over every one of them on every scheduled review. A 64 KiB tail
    holds many whole records; if it somehow held none, the caller falls back to mtime.
    """
    try:
        with path.open("rb") as fh:
            size = fh.seek(0, 2)
            fh.seek(max(0, size - EDGE))
            found = TS_RE.findall(_decode(fh.read()))
    except OSError:
        return None
    return parse_ts(found[-1]) if found else None


class Transcript:
    """One transcript file with everything the census needs to place it in time."""

    __slots__ = ("path", "session", "slug", "subagent", "mtime", "first", "last", "scan")

    def __init__(self, path, session, slug, subagent, mtime):
        self.path = path
        self.session = session
        self.slug = slug
        self.subagent = subagent
        self.mtime = mtime  # dt.date, UTC
        self.first: dt.datetime | None = None
        self.last: dt.datetime | None = None
        self.scan = False

    @property
    def order(self) -> tuple:
        """Oldest-first key. The file's own clock where it has one, else its mtime."""
        return (self.first.isoformat() if self.first else self.mtime.isoformat(), str(self.path))


class Index:
    """The transcript census for one window, computed once and shared across tools.

    WHY NOT MTIME: a transcript's mtime is not its content's age. A client can rewrite
    transcript mtimes - opening or displaying a transcript can move its mtime to around
    the present. Were a session in the window when its main transcript's mtime fell
    inside it, old sessions touched that way would enter a later window's denominator and
    inflate the "used in N of M sessions" ratio that decides a pilot. So a session is in
    the window when its own record interval overlaps it: record timestamps are written
    once, when the record is, and nothing rewrites them.

    mtime survives as a PRE-FILTER only, and only in the direction where it cannot lie:
    a file's mtime can be later than its content (a rewrite, a copy, a backup restore)
    but never earlier, so `mtime < since` really does mean "no record inside the window".
    """

    def __init__(self, files, since: dt.date, until: dt.date) -> None:
        self.since, self.until = since, until
        self.transcripts: list[Transcript] = []
        self.sessions: set[str] = set()
        # TRANSCRIPTS, not sessions - the loop below runs once per FILE, so the name says
        # transcripts. The count is of main transcripts whose mtime falls
        # in the window while their own records do not, which is a different quantity from
        # the sessions those files stand for: a session with a second, in-window transcript
        # is not excluded from the census by one of its files being. Naming a file count
        # after sessions invites subtracting it from the denominator, which would be wrong.
        self.transcripts_excluded_by_timestamp = 0
        self.dated_by_mtime = 0
        # A CEILING on how far back the evidence reaches, not the edge - see head_clock.
        self.oldest_record_by_head_scan: dt.date | None = None

        for path, session_id, slug, subagent in files:
            try:
                mtime = utc_date(path.stat().st_mtime)
            except OSError:
                continue
            t = Transcript(path, session_id, slug, subagent, mtime)
            if subagent:
                # Sidechains are not sessions and never enter the denominator, so they
                # are not worth two extra reads each: the mtime pre-filter is enough.
                t.scan = mtime >= since
                if t.scan:
                    self.transcripts.append(t)
                continue

            # Read the head even for files the pre-filter would drop: the retention
            # check needs the oldest record that exists ON DISK, and that is by
            # definition in a file older than the window.
            t.first, earliest = head_clock(path)
            # The census keeps the FIRST record (the session's own start); the retention
            # horizon takes the EARLIEST in the head, which a replayed history can push
            # back. Deliberately not the same value: feeding a replayed, older timestamp
            # into a later session's overlap test would put that session into an older
            # window's denominator, which is the mtime-inflation defect wearing a new hat.
            if earliest and (
                self.oldest_record_by_head_scan is None
                or earliest.date() < self.oldest_record_by_head_scan
            ):
                self.oldest_record_by_head_scan = earliest.date()
            if mtime < since:
                continue
            t.last = last_timestamp(path)

            by_mtime = since <= mtime <= until
            if t.first and t.last:
                overlaps = t.first.date() <= until and t.last.date() >= since
            else:
                # No parseable timestamp at either end: fall back to the mtime rule rather
                # than silently dropping the session out of the denominator.
                overlaps = by_mtime
                self.dated_by_mtime += 1
            if overlaps:
                self.sessions.add(session_id)
            elif by_mtime:
                self.transcripts_excluded_by_timestamp += 1
            # A file whose own interval misses the window holds no in-window record, so
            # it is not worth streaming either.
            t.scan = overlaps
            if t.scan:
                self.transcripts.append(t)

        self.transcripts.sort(key=lambda t: t.order)


# --------------------------------------------------------- reconciliation (drift)

# TWO PARSERS FOR ONE FACT. A second invocation table can be derived by another parser
# from the same .jsonl files this script reads, with the same question in mind: which
# tool did this call invoke. Two implementations of one fact drift silently, and the
# drift is invisible precisely because each is confident on its own. So the duplication
# is turned into an instrument: --reconcile counts the table's rows under this entry's
# matchers and reports the disagreement per matcher kind.
#
# What it is NOT: a source of truth. The table is a snapshot with a generation time, so
# both sides are counted only up to that time - a call made after it cannot be in the
# table - and its age is printed with the counts.
#
# The input is invocation table format, version 1, specified in docs/concepts.md
# ("Cross-checking against an invocation table"): `derived/invocations.jsonl` (one row
# per call, with `timestamp`, `tool`, `exe`, `skill` and `first_seen`) and
# `derived/derive.json` (`generated_at`, and optionally `format`, which is accepted and
# not acted on), under the profile's `[paths].transcript_index`. Anything that writes
# those two files can be cross-checked.
#
# SCRIPT NAMES. command_identities() names the script an interpreter runs, so a
# script-named glob is compared like any other. A table that records only the
# interpreter reads as drift on such a glob, which is the right signal: excusing it
# would hide exactly the disagreement this check exists to surface.
RECONCILE_KINDS = ("command", "skill", "mcp")
_INDEX_CACHE: dict[str, tuple[list[tuple], str | None]] = {}


def load_transcript_index(store: Path) -> tuple[list[tuple], str | None] | None:
    """(rows, generated_at) from an invocation table (format version 1) under `store`,
    or None if absent.

    Cached per store path: --all reconciles every entry against the same table, which
    can be large, and reading it once per tool would dominate the run.

    Only `first_seen` rows are kept - the table marks replayed copies, and counting
    them would compare our de-duplicated numbers against its raw ones and report drift
    that is really just the two sides answering different questions.
    """
    key = str(store)
    if key in _INDEX_CACHE:
        return _INDEX_CACHE[key]
    table = store / "derived" / "invocations.jsonl"
    if not table.is_file():
        return None
    generated_at = None
    meta = store / "derived" / "derive.json"
    if meta.is_file():
        try:
            generated_at = json.loads(meta.read_text(encoding="utf-8")).get("generated_at")
        except (OSError, ValueError):
            generated_at = None
    rows: list[tuple] = []
    with table.open(encoding="utf-8", errors="replace") as fh:
        for line in fh:
            try:
                r = json.loads(line)
            except ValueError:
                continue
            if not r.get("first_seen"):
                continue
            ts = r.get("timestamp")
            if not isinstance(ts, str):
                continue
            exe = r.get("exe")
            rows.append(
                (
                    ts[:10],
                    utc_moment(ts),
                    r.get("tool") or "",
                    tuple(e for e in exe if isinstance(e, str)) if isinstance(exe, list) else (),
                    r.get("skill") if isinstance(r.get("skill"), str) else None,
                )
            )
    _INDEX_CACHE[key] = (rows, generated_at)
    return _INDEX_CACHE[key]


def index_counts(
    rows: list[tuple],
    since: dt.date,
    until: dt.date,
    globs: list[str],
    skill_globs: list[str],
    command_globs: list[str],
    cutoff: dt.datetime | None = None,
) -> dict[str, int]:
    """The index's count under each matcher kind, over the same window.

    `cutoff` is the index's own generation time: a record after it cannot be in the
    index, so neither side counts one (see `our_counts`).
    """
    lo, hi = since.isoformat(), until.isoformat()
    out = dict.fromkeys(RECONCILE_KINDS, 0)
    for day, moment, tool_name, exe, skill in rows:
        if not (lo <= day <= hi):
            continue
        if cutoff is not None and moment is not None and moment > cutoff:
            continue
        if command_globs and any(matches(e, command_globs) for e in exe):
            out["command"] += 1
        if skill_globs and skill and matches(skill, skill_globs):
            out["skill"] += 1
        if globs and matches(tool_name, globs):
            out["mcp"] += 1
    return out


def our_counts(
    in_window: list[dict],
    command_globs: list[str] | None = None,
    cutoff: dt.datetime | None = None,
) -> dict[str, int]:
    """The same three counts from this run, keyed the same way.

    `command_globs` narrows the `command` count to the identities those globs match, so
    the comparison can be run over only the globs the index can express. None
    means "count every cmd: row", which is what a report with nothing excluded wants.

    `cutoff` stops the count at the index's generation time. The transcripts keep
    growing after the index is derived, so counting the whole window would report every
    call made since then as a disagreement between the scanners.
    """
    out = dict.fromkeys(RECONCILE_KINDS, 0)
    for i in in_window:
        if cutoff is not None:
            moment = utc_moment(i.get("at"))
            if moment is not None and moment > cutoff:
                continue
        name = i["tool"]
        if name.startswith("cmd:"):
            if command_globs is not None and not matches(name[4:], command_globs):
                continue
            out["command"] += 1
        elif name.startswith("skill:"):
            out["skill"] += 1
        else:
            out["mcp"] += 1
    return out


def reconcile_lines(tool_name: str, rec: dict | None) -> list[str]:
    """The agreement read-out, one line per matcher kind. Console form."""
    if not rec:
        return []
    age = f", derived {rec['age_hours']}h ago" if rec.get("age_hours") is not None else ""
    out = [
        f"reconcile {tool_name} vs invocation table ({rec['generated_at'] or 'unknown date'}{age}):"
    ]
    if not rec["kinds"]:
        return out + ["  (no comparable matcher kind on this entry)"]
    for k in rec["kinds"]:
        verdict = "agree" if k["relative"] <= rec["tolerance"] else "DRIFT"
        out.append(
            f"  {k['kind']:<8} ours {k['ours']:>6}  index {k['index']:>6}  "
            f"delta {k['delta']:+d} ({k['relative']:.1%}) {verdict}"
        )
    return out


def utc_moment(raw: str | None) -> dt.datetime | None:
    """A timestamp as an aware UTC datetime; one written without a zone is read as UTC."""
    ts = parse_ts(raw)
    if ts is None:
        return None
    return ts.replace(tzinfo=dt.UTC) if ts.tzinfo is None else ts.astimezone(dt.UTC)


def derive_age_hours(generated_at: str | None) -> float | None:
    """How old the index is, in hours. In days, an index derived this morning read as
    "0d ago" however many calls had been made since."""
    ts = utc_moment(generated_at)
    if ts is None:
        return None
    return round((dt.datetime.now(dt.UTC) - ts).total_seconds() / 3600, 1)


# ------------------------------------------------------------------------ statistics


def pct(values: list[float], q: float) -> float | None:
    if not values:
        return None
    if len(values) == 1:
        return round(values[0], 1)
    s = sorted(values)
    idx = max(0, min(len(s) - 1, int(-(-len(s) * q // 1)) - 1))
    return round(s[idx], 1)


def med(values: list[float]) -> float | None:
    return round(statistics.median(values), 1) if values else None


def utc_date(epoch: float) -> dt.date:
    return dt.datetime.fromtimestamp(epoch, dt.UTC).date()


# --------------------------------------------------------------------------- reports


def fmt_rate(num: int, den: int) -> str:
    return f"{num}/{den} ({(100.0 * num / den):.0f}%)" if den else f"{num}/0 (n/a)"


def opportunity_section(d: dict) -> list[str]:
    """Opportunity vs use: the salience read-out, or the reason there isn't one."""
    m = d["metrics"]
    declared = (
        d.get("opportunity_match")
        or d.get("opportunity_match_skill")
        or (d.get("opportunity_match_command"))
    )
    L = [
        "## Opportunity vs use (salience)",
        "",
        "The census above divides by every session on the machine, which reads a "
        "specialist tool as unused however diligently it is reached for. Zero use has "
        "three readings - the work never called for it, it was not mounted, or it was "
        "there and applicable and nobody reached for it - and a count of invocations "
        "separates none of them.",
        "",
        "`[telemetry].opportunity_match*` names the calls that mark a session where this "
        "tool WOULD have applied. It separates the first reading from the other two. It "
        "does NOT separate 'not mounted' from 'never thought of': nothing here can, and "
        "the ratio below must not be read as a salience measurement on its own.",
        "",
    ]
    if not declared:
        return L + [
            "No opportunity matcher is declared for this entry, so the denominator is "
            "still every session and a low ratio above cannot be attributed. Declaring "
            "one is a judgement about when the tool applies and is deliberately never "
            "guessed - write it where the entry's own notes already say it.",
            "",
        ]
    L += [
        "- opportunity matchers: "
        + ", ".join(
            md_code(g)
            for g in (
                *d.get("opportunity_match", []),
                *d.get("opportunity_match_skill", []),
                *d.get("opportunity_match_command", []),
            )
        ),
        "",
        "| metric | value |",
        "|---|---|",
        f"| sessions with an opportunity | {m['opportunity_sessions']} |",
        f"| of those, sessions that used the tool | "
        f"{fmt_rate(m['sessions_with_use_among_opportunity'] or 0, m['opportunity_sessions'])} |",
        f"| taken ratio | {m['taken_ratio'] if m['taken_ratio'] is not None else 'n/a'} |",
        f"| opportunity invocations | {m['opportunity_invocations']} |",
        "",
    ]
    if m["opportunity_tools"]:
        L += [
            "The opportunity tools actually hit - printed because a matcher that never "
            "fires is indistinguishable from an occasion that never arose:",
            "",
            "| opportunity tool | invocations | sessions |",
            "|---|---|---|",
        ]
        L += [
            f"| {md_code(t['tool'])} | {t['invocations']} | {t['sessions']} |"
            for t in m["opportunity_tools"]
        ]
    else:
        L.append(
            "No opportunity tool was invoked in the window. Either the occasion never "
            "arose, or the matchers name something this corpus does not contain - check "
            "the names against a real transcript before reading the zero as the former."
        )
    L.append("")
    return L


def render_md(d: dict) -> str:
    w, sc, m = d["window"], d["scan"], d["metrics"]
    L: list[str] = [
        f"# Field report - {d['tool']}",
        "",
        GEN_NOTE,
        "",
        f"**{DESCRIPTIVE_BANNER}**",
        "",
        f"- window: `{w['since']}` .. `{w['until']}` "
        f"({w['days']} day{'' if w['days'] == 1 else 's'})",
        f"- environment: {md_code(d['environment'])}  claude_home: {md_code(d['claude_home'])}",
        "- matchers: " + ", ".join(md_code(g) for g in d["match"]),
        *(
            [
                "- also runs where no transcript can see it: "
                + ", ".join(md_code(s) for s in d["also_runs_in"])
            ]
            if d.get("also_runs_in")
            else []
        ),
        f"- scan: {sc['transcripts_on_disk']} transcripts on disk, "
        f"{sc['in_time_window']} that could hold an in-window record (a main transcript "
        f"whose own first..last interval overlaps it, or a sidechain whose mtime does), "
        f"{sc['prescan_hits']} past the "
        f"byte prescan, {sc['parsed']} streamed; {sc['malformed_lines']} malformed lines "
        f"skipped; {sc['wall_clock_s']}s wall clock",
        "",
        "## Opportunity-frequency census",
        "",
        "The decisive number for a small-effect tool is not the error rate, it is how "
        "often a session ever touched the tool at all.",
        "",
        "Denominator: a session counts as in-window when the interval between its main "
        "transcript's FIRST and LAST record overlaps the window - the transcript's own "
        "clock, not the file's mtime. mtime survives only as a pre-filter, in the one "
        "direction where it cannot lie (a file's mtime can be later than its content, "
        "never earlier). The rule exists because a client can rewrite transcript mtimes "
        "- opening or displaying a transcript can move its mtime to around the present - "
        "which would move old sessions into later windows under an mtime rule.",
        "",
        "It is still a ceiling rather than a count of hand-driven sessions: headless and "
        "scripted sessions are transcripts too. "
        "Sessions with use are dated by the invocation's own timestamp.",
        "",
        "| metric | value |",
        "|---|---|",
        f"| sessions in window | {m['sessions_in_window']} |",
        f"| transcripts excluded by the timestamp rule (mtime alone would have counted "
        f"them) | {m['transcripts_excluded_by_timestamp']} |",
        f"| main transcripts still dated by mtime (no parseable timestamp at either end) "
        f"| {m['sessions_dated_by_mtime']} |",
        f"| sessions with any use | {fmt_rate(m['sessions_with_use'], m['sessions_in_window'])} |",
        f"| of those, outside the census (sidechain-only) "
        f"| {m['sessions_with_use_outside_census']} |",
        f"| invocations | {m['invocations']} |",
        f"| replayed copies dropped | {m['replayed_dropped']} |",
        f"| invocations per session-with-use | {m['invocations_per_used_session'] or 'n/a'} |",
        f"| days with use / days in window | {m['days_with_use']}/{w['days']} |",
        f"| errors | {fmt_rate(m['errors'], m['resolved'])} of resolved calls |",
        f"| calls with no matching result | {m['unresolved']} |",
        f"| main-session vs subagent | {m['main_invocations']} / {m['subagent_invocations']} |",
        f"| first seen | {m['first_seen'] or '-'} |",
        f"| last seen | {m['last_seen'] or '-'} |",
        "",
    ]

    L += opportunity_section(d)

    rec = d.get("reconcile")
    if rec:
        L += [
            "## Cross-check against a second invocation table",
            "",
            "Two parsers read the same transcripts for the same fact, so the duplication "
            "is used as a drift detector rather than left to diverge quietly. The "
            "table is a SNAPSHOT with a generation time, so both sides are counted only "
            "up to it, and its age is shown here.",
            "",
            f"- index location (`[paths].transcript_index`): {md_code(rec['store'])}",
            f"- derived at: {rec['generated_at'] or 'unknown'}"
            + (f" ({rec['age_hours']}h ago)" if rec.get("age_hours") is not None else ""),
            "- compared: "
            + (
                f"records up to {rec['compared_up_to']} only, on both sides - a call made "
                "after the index was derived cannot be in it"
                if rec.get("compared_up_to")
                else "the whole window (the index's generation time is unknown)"
            ),
            "",
        ]
        if rec.get("kinds"):
            L += ["| matcher kind | ours | index | delta | relative |", "|---|---|---|---|---|"]
            for k in rec["kinds"]:
                L.append(
                    f"| {k['kind']} | {k['ours']} | {k['index']} | {k['delta']:+d} | "
                    f"{k['relative']:.1%} |"
                )
        else:
            L.append("No matcher kind on this entry is comparable against the index.")
        L.append("")

    L += ["## Per-tool breakdown", ""]
    if m["per_tool"]:
        L += [
            "| tool | invocations | sessions | errors | median ms | p90 ms |",
            "|---|---|---|---|---|---|",
        ]
        for t in m["per_tool"]:
            L.append(
                f"| {md_code(t['tool'])} | {t['invocations']} | {t['sessions']} | "
                f"{t['errors']} | {t['median_ms'] if t['median_ms'] is not None else '-'} | "
                f"{t['p90_ms'] if t['p90_ms'] is not None else '-'} |"
            )
    else:
        L.append("No individual tool under these matchers was invoked in the window.")
    L.append("")

    ex = m["exposure"]
    L += ["## Exposure vs use", ""]
    if ex["declared"] is None:
        L += [
            "`[telemetry].exposed` is not declared for this tool, so dead weight cannot "
            "be computed: only tools that were used can be observed. Declare the exposed "
            "tool names to get an unused list.",
            "",
        ]
    else:
        L += [
            "Compared on the leaf tool name (the part after the last `__`), because the "
            "mount prefix changes with how the server is mounted while the tool surface "
            "does not.",
            "",
            f"- declared exposed surface: {len(ex['declared'])}",
            f"- ever used: {len(ex['used'])}",
            f"- never used (dead weight): {len(ex['unused'])}",
            "",
        ]
        if ex["unused"]:
            L += [f"  - {md_code(n)}" for n in ex["unused"]] + [""]
        if ex["undeclared_used"]:
            L += [
                "Used but not declared exposed (the declaration is stale):",
                *[f"  - {md_code(n)}" for n in ex["undeclared_used"]],
                "",
            ]

    L += ["## Where it appeared", ""]
    if m["slugs"]:
        L += ["| project slug | invocations |", "|---|---|"]
        L += [f"| {md_code(s['slug'])} | {s['invocations']} |" for s in m["slugs"]]
    else:
        L.append("Nowhere.")
    L.append("")

    px = d["pilot_exit"]
    L += ["## Pilot exit criteria (verbatim, as pre-registered)", ""]
    if px is not None and not d.get("pilot_exit_evaluated"):
        L += [
            f"Retained from an earlier pilot and NOT evaluated: the entry is at "
            f'`ring = "{d["ring"]}"`. They are kept as the record of what was promised '
            "before the data existed, and they apply again if it is re-piloted.",
            "",
        ]
    if px is None and d["ring"] != "pilot":
        L += [
            f'Not a pilot: the entry is at `ring = "{d["ring"]}"`, and only a pilot owes '
            "pre-registered exit criteria.",
            "",
        ]
    elif px is None:
        L += [
            "No `[pilot_exit]` block on this entry. Without pre-registered criteria the "
            "numbers above cannot settle anything - criteria written after the data are "
            "not criteria.",
            "",
        ]
    else:
        for k in ("review_after_days", "adopt_if", "decline_if"):
            if k in px:
                L.append(f"- **{k}**: {px[k]}")
        for k, v in sorted(px.items()):
            if k not in ("review_after_days", "adopt_if", "decline_if"):
                L.append(f"- **{k}**: {v}")
        L.append("")

    L += ["## Mechanical checks", ""]
    if d["checks"]:
        L += ["| check | verdict | detail |", "|---|---|---|"]
        for c in d["checks"]:
            L.append(
                f"| {md_text(c['check'])} | {md_text(c['verdict'])} | {md_text(c['detail'])} |"
            )
    else:
        L.append("Nothing here is mechanically checkable.")
    L += [
        "",
        "`adopt_if` / `decline_if` prose is deliberately NOT evaluated: it is a judgement, "
        "and this script never transitions a ring. A ring moves only in a radar session "
        "with a human, recorded as a dated `[[history]]` entry with evidence.",
        "",
        "## Findings",
        "",
    ]
    L += [f"- {md_code(f)}" for f in d["findings"]] or ["- none"]
    L.append("")
    return "\n".join(L)


# ------------------------------------------------------------------------------ main


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="radar field",
        description="Post-hoc field telemetry for an entry, at any ring, mined from "
        "session transcripts.",
    )
    ap.add_argument("tool", nargs="?", help="tool name as in tools/<name>.toml")
    ap.add_argument(
        "--data-root",
        help="the radar data root, instead of searching upwards for radar.toml. For CI "
        "and nothing else; it still has to name a directory that carries the "
        "marker",
    )
    ap.add_argument("--since", help="YYYY-MM-DD; default [telemetry].since")
    ap.add_argument("--until", help="YYYY-MM-DD; default today (UTC)")
    ap.add_argument("--claude-home", help="override the environment's [paths].claude_home")
    ap.add_argument(
        "--env",
        type=environment_name,
        help="environment name (default: the top-level default_environment key of radar.toml)",
    )
    ap.add_argument(
        "--match",
        action="append",
        help="override [telemetry].match (repeatable) - for probing the mechanism",
    )
    ap.add_argument(
        "--match-skill",
        action="append",
        help="override [telemetry].match_skill (repeatable): globs matched against "
        "a Skill call's input.skill, which is how own-ring tools are reached",
    )
    ap.add_argument(
        "--match-command",
        action="append",
        help="override [telemetry].match_command (repeatable): globs matched against the "
        "RESOLVED CHAIN of executables a Bash/PowerShell command invokes - `uv run ruff "
        "check` resolves to uv AND ruff, `python -m pytest` to python AND pytest - which "
        "is how a `cli` artifact is visible at all. A DECLARED glob is also expanded to "
        "its module spelling (pre-commit -> pre_commit); an override given here is "
        "measured LITERALLY, so a probe answers the question you typed",
    )
    ap.add_argument(
        "--reconcile",
        action="store_true",
        help="cross-check this run's counts against a second invocation table (invocation "
        "table format, version 1, under [paths].transcript_index), per matcher kind and up "
        "to the table's own generation time, and warn on drift above 2%% - two parsers for "
        "one fact disagree silently otherwise",
    )
    ap.add_argument(
        "--all",
        action="store_true",
        help="run every tools/*.toml entry that declares a matcher and print one summary "
        "table - the line a scheduled review runs, so a declared matcher that was never "
        "run cannot go "
        "unnoticed until the transcripts it needed are pruned",
    )
    ap.add_argument(
        "--include-inactive",
        action="store_true",
        help="with --all, also run entries at ring=observe/discard (skipped by default: "
        "they claim nothing, so nothing about them is being checked)",
    )
    ap.add_argument(
        "--out-dir",
        help="write the reports under this directory instead of field/ (still one "
        "subdirectory per tool). For verification runs and probes: field/ is TRACKED, so "
        "re-running a committed window to check a number rewrites the very artefact the "
        "check compares against",
    )
    ap.add_argument("--json", action="store_true", help="print the machine report to stdout")
    return ap


def run_tool(
    tool: dict,
    args: argparse.Namespace,
    env: dict | None,
    home: Path,
    files: list,
    index_cache: dict,
) -> dict | None:
    """One entry's field report, written to field/<tool>/ and returned.

    None means the entry could not be measured at all (a name that is not an
    identifier, no matcher, no window) - a condition the caller reports as a FAIL.
    Everything softer is a finding inside the document, so a --all run keeps going and
    reports at the end.
    """
    name = str(tool.get("name"))
    # The report directory is named after the entry, so a name with a path separator or
    # a leading dot would choose where the report is written. Checked here because the
    # field report does not run validate(); the rule is validate()'s own.
    if not is_plain_name(name):
        print(f"[FAIL] {name!r}: not a valid entry name ({NAME_RULE}) - no report written")
        return None
    # The report lands in field/<subdir>/, and field/ is TRACKED. A machine-local entry's
    # NAME must not travel, so its report directory is named for its `redact_as`
    # placeholder, not the entry name - otherwise the private name would be written into a
    # tracked path that redaction of the file CONTENT cannot reach, and the gate would
    # fail on a path the engine itself wrote. An entry with no placeholder cannot be
    # placed safely, so it is refused by name here rather than written to field/<name>/.
    # The placeholder is a directory name, so it is held to the entry-name rule too (a
    # separator or `..` in it would choose where the report is written), and it may not
    # contain the name it stands in for (radar_lib.placeholder_error).
    report_subdir = name
    if tool.get("_local"):
        redact_as = str(tool.get("redact_as") or "").strip()
        if not redact_as:
            print(
                f"[FAIL] {name!r}: a machine-local entry (tools.local/) with no `redact_as` "
                "- its name would be written into the tracked field/ path. Declare "
                "`redact_as` so the report directory can carry the placeholder instead"
            )
            return None
        why = placeholder_error(tool, redact_as)
        if why:
            print(
                f"[FAIL] {name!r}: `redact_as` {redact_as!r} is not a valid placeholder "
                f"({why}) - no report written"
            )
            return None
        report_subdir = redact_as
    findings: list[str] = []
    tel = tool.get("telemetry")
    match = args.match or (tel or {}).get("match") or []
    # Own-ring tools are reached through their skills, not through MCP tools, so
    # `match_skill` globs are matched against a Skill call's `input.skill`.
    skill_globs = list(args.match_skill or (tel or {}).get("match_skill") or [])
    # `match_command` globs are matched against the RESOLVED CHAIN of executables a shell
    # command invokes, which is the only way a CLI-artifact tool appears in a transcript
    # at all. Expanded once, here, so the prescan needles, the scan, --reconcile's count
    # of the index and the document's own `match_command` field all use one set.
    #
    # THE EXPANSION IS FOR DECLARED GLOBS ONLY. It exists because a distribution name is
    # not a module name and an ENTRY is written under the distribution name - the name the
    # tool installs and publishes under - so `pre-commit` could not match the module
    # form, which on some machines is the only one. A `--match-command` override is a
    # probe: someone typed a glob to find out what it matches, and silently measuring a
    # second glob they did not type makes the answer unusable for the question they
    # asked. So an override is literal, and --help says so.
    if args.match_command:
        command_globs = list(args.match_command)
    else:
        command_globs = expand_command_globs(list((tel or {}).get("match_command") or []))
    # Surfaces a transcript cannot record: a git hook fires inside `git commit`, a CI
    # job runs on a server. Declaring them does not add invocations - nothing can - it
    # changes what a low count is allowed to conclude.
    also_runs_in = [str(s) for s in ((tel or {}).get("also_runs_in") or [])]
    # OPPORTUNITY. Declared-only - there is no CLI override, because these are a
    # judgement about when the tool would have applied and a probe flag would invite
    # inventing one per run to make a ratio come out.
    opportunity = Matchers(
        list((tel or {}).get("opportunity_match") or []),
        list((tel or {}).get("opportunity_match_skill") or []),
        expand_command_globs(list((tel or {}).get("opportunity_match_command") or [])),
    )
    if not match and not skill_globs and not command_globs:
        print(
            f"[FAIL] {name}: no [telemetry].match - add a [telemetry] block with "
            '`match` (tool-name globs, e.g. "mcp__plugin_x_y__*") and `since` '
            "(YYYY-MM-DD), or pass --match to probe"
        )
        return None

    since_raw = args.since or (tel or {}).get("since")
    if not since_raw:
        print(f"[FAIL] {name}: no --since and no [telemetry].since")
        return None
    try:
        since = dt.date.fromisoformat(str(since_raw))
        until = dt.date.fromisoformat(args.until) if args.until else dt.datetime.now(dt.UTC).date()
    except ValueError as e:
        print(f"[FAIL] {name}: bad date - {e}")
        return None
    if until < since:
        print(f"[FAIL] {name}: --until {until} precedes since {since}")
        return None

    globs = list(match)
    use = Matchers(globs, skill_globs, command_globs)
    # Prescan needles are a SUPERSET filter: a transcript is parsed only if its raw bytes
    # contain one. A command glob's needle is the executable name itself, which appears
    # inside input.command, so the same mechanism finds it.
    #
    # ONE HOLE, a property of resolving chains rather than reading heads: resolution can
    # name an executable the text does not contain - `uv run -m pytest` and `uv run
    # analyse.py` both resolve through "python", which is nowhere in those command lines.
    # So when a command glob matches "python" itself the needles are not a superset,
    # and the prescan is turned off for that entry rather than left to drop
    # real matches.
    #
    # The opportunity matchers' needles go in the same set, because a session that only
    # ever took the OPPORTUNITY - the whole population the ratio is about - contains none
    # of the use needles, and a prescan that filtered on those alone would drop exactly
    # the files the new number needs. The cost is real: more files pass the filter and get
    # parsed, which the `scan` block reports.
    needles = sorted(matcher_needles(use) | matcher_needles(opportunity))
    if any(n == "" for n in needles):
        findings.append(
            f"[WARN] {name}: a matcher has no literal prefix; the byte prescan is "
            "disabled and every transcript in the window is parsed"
        )
        byte_needles: list[bytes] = []
    elif any(fnmatch("python", g) for g in (*use.command, *opportunity.command)):
        findings.append(
            f"[WARN] {name}: a command matcher matches `python`, which a chain can "
            "resolve through without the word in the command line; the byte prescan is "
            "disabled and every transcript in the window is parsed"
        )
        byte_needles = []
        # The same hole applies line by line inside a parsed file, so every line is
        # read there too.
        needles = [""]
    else:
        byte_needles = [n.encode() for n in needles]
    overlap = max((len(n) for n in byte_needles), default=1) - 1

    t0 = time.monotonic()
    # The census depends only on the window, never on the entry, so a --all run over one
    # window computes it once. It is the expensive half: two bounded reads per main
    # transcript, times every transcript on disk, times every tool would be silly.
    key = (since, until)
    if key not in index_cache:
        index_cache[key] = Index(files, since, until)
    index = index_cache[key]
    invocations: list[dict] = []
    replayed: list[dict] = []
    chances: list[dict] = []
    malformed = 0
    n_in_window = len(index.transcripts)
    n_prescan = n_parsed = 0
    # THE CENSUS, and it is the index's alone. Growing it with every session an entry's
    # own invocations touched would make the denominator ENTRY-DEPENDENT: in a --all table
    # each row would divide by a slightly different number, so the column that looks like
    # one census would be several. The extra
    # ids come from sidechain transcripts (subagents, workflows) whose parent session's
    # own transcript is absent or falls outside the window - real use, but not a session
    # of its own, and never a reason to move one row's denominator. Reported separately.
    sessions_in_window: set[str] = set(index.sessions)
    # One id set for the whole scan; index.transcripts is ordered oldest-first, so a
    # tool_use that appears in two files is credited to the file that saw it first.
    seen_ids: set[str] = set()
    opportunity_seen_ids: set[str] = set()

    for t in index.transcripts:
        if byte_needles and not prescan_hit(t.path, byte_needles, overlap):
            continue
        n_prescan += 1
        n_parsed += 1
        got = scan_file(
            t.path,
            t.session,
            t.slug,
            t.subagent,
            use,
            needles,
            seen_ids,
            opportunity,
            opportunity_seen_ids,
        )
        malformed += got.malformed
        invocations.extend(got.invocations)
        replayed.extend(got.replayed)
        chances.extend(got.opportunities)

    if not byte_needles:
        n_prescan = n_in_window

    def dated_in_window(rows: list[dict]) -> list[dict]:
        return [r for r in rows if r["_ts"] is not None and since <= r["_ts"].date() <= until]

    in_window = dated_in_window(invocations)
    replayed_in_window = len(dated_in_window(replayed))
    chances_in_window = dated_in_window(chances)
    for i in in_window:
        i.pop("_ts", None)
    for i in chances_in_window:
        i.pop("_ts", None)
    wall = round(time.monotonic() - t0, 1)

    used_sessions = {i["session"] for i in in_window}
    used_outside_census = used_sessions - sessions_in_window
    resolved = [i for i in in_window if i["resolved"]]
    errors = [i for i in resolved if i["is_error"]]
    lat_all = [i["latency_ms"] for i in in_window if i["latency_ms"] is not None]
    days_with_use = {i["at"][:10] for i in in_window if i["at"]}
    stamps = sorted(i["at"] for i in in_window if i["at"])

    names = sorted({i["tool"] for i in in_window})
    # Ordered on the typed locals rather than by reading the fields back out of the dict.
    # The row holds strings, ints and optional floats, so its value type is a union that
    # has no unary minus - while `len(rows)` is an int right here, and `n` a string.
    counted: list[tuple[int, str, dict]] = []
    for n in names:
        rows = [i for i in in_window if i["tool"] == n]
        lat = [i["latency_ms"] for i in rows if i["latency_ms"] is not None]
        counted.append(
            (
                len(rows),
                n,
                {
                    "tool": n,
                    "invocations": len(rows),
                    "sessions": len({i["session"] for i in rows}),
                    "errors": sum(1 for i in rows if i["is_error"]),
                    "median_ms": med(lat),
                    "p90_ms": pct(lat, 0.9),
                },
            )
        )
    counted.sort(key=lambda item: (-item[0], item[1]))
    per_tool = [row for _count, _name, row in counted]

    slug_counts: dict[str, int] = {}
    for i in in_window:
        slug_counts[i["slug"]] = slug_counts.get(i["slug"], 0) + 1
    slugs = [
        {"slug": s, "invocations": c}
        for s, c in sorted(slug_counts.items(), key=lambda kv: (-kv[1], kv[0]))
    ]

    # Exposure is compared on the leaf name: the mount prefix varies with how the server
    # was mounted - comparing full names would report the whole surface unused after a
    # remount - while the tool surface it exposes does not.
    def leaf(n: str) -> str:
        return n.rsplit("__", 1)[-1]

    declared = (tel or {}).get("exposed")
    used_leaves = {leaf(n) for n in names}
    declared_leaves = {leaf(n) for n in declared} if declared else set()
    exposure = {
        "declared": list(declared) if declared else None,
        "used": sorted(used_leaves),
        "unused": sorted(declared_leaves - used_leaves) if declared else [],
        "undeclared_used": sorted(used_leaves - declared_leaves) if declared else [],
    }

    # ------------------------------------------------------------------- opportunity
    #
    # THE DENOMINATOR USE NEVER HAD. `sessions_with_use / sessions_in_window` divides by
    # every session on the machine, so a tool that applies to one kind of work reads as
    # unused however diligently it is reached for. Zero use has three readings - the work
    # never called for it, it was not mounted, or it was there and nobody thought of it -
    # and the ratio above cannot separate them. The opportunity matchers name calls that
    # mark a session where the tool WOULD have applied, which separates the first reading
    # from the other two. It does not separate the second from the third; nothing here
    # can, and pretending otherwise would be the tidy lie this script exists to remove.
    opportunity_sessions = {i["session"] for i in chances_in_window}
    took_it = opportunity_sessions & used_sessions
    opportunity_names = sorted({i["tool"] for i in chances_in_window})
    opportunity_tools = sorted(
        (
            {
                "tool": n,
                "invocations": sum(1 for i in chances_in_window if i["tool"] == n),
                "sessions": len({i["session"] for i in chances_in_window if i["tool"] == n}),
            }
            for n in opportunity_names
        ),
        key=lambda r: (-r["invocations"], r["tool"]),
    )

    days = (until - since).days + 1
    metrics = {
        "sessions_in_window": len(sessions_in_window),
        # Transcripts whose mtime is in the window while their own records are not: what
        # a denominator dated by mtime would have counted wrongly. Reported rather than
        # silently dropped, so a reader can see how far the two datings differ on this
        # run. TRANSCRIPTS, and the name says so: it counts FILES, which is not the same
        # quantity as the sessions they stand for.
        "transcripts_excluded_by_timestamp": index.transcripts_excluded_by_timestamp,
        # Main transcripts with no parseable timestamp at either end, which are dated by
        # the mtime rule instead. Kept in the census rather than dropped - dropping would
        # shrink the denominator on a parsing failure, which flatters every ratio - and
        # surfaced in the report because a census that rests on the mtime rule for part
        # of its rows should say how large that part is.
        "sessions_dated_by_mtime": index.dated_by_mtime,
        # Matching calls dropped because the same tool_use id had already been counted
        # in an older transcript - a resumed or forked session replays the session it
        # continues.
        "replayed_dropped": replayed_in_window,
        "sessions_with_use": len(used_sessions),
        # Sessions with use that the census does not contain - sidechain-only, or a parent
        # whose main transcript is gone. Reported rather than folded into the denominator,
        # which is what made the denominator entry-dependent.
        "sessions_with_use_outside_census": len(used_outside_census),
        "invocations": len(in_window),
        "invocations_per_used_session": (
            round(len(in_window) / len(used_sessions), 1) if used_sessions else None
        ),
        "resolved": len(resolved),
        "unresolved": len(in_window) - len(resolved),
        "errors": len(errors),
        "error_rate": round(len(errors) / len(resolved), 3) if resolved else None,
        "latency_median_ms": med(lat_all),
        "latency_p90_ms": pct(lat_all, 0.9),
        "days_with_use": len(days_with_use),
        "main_invocations": sum(1 for i in in_window if not i["subagent"]),
        "subagent_invocations": sum(1 for i in in_window if i["subagent"]),
        "first_seen": stamps[0] if stamps else None,
        "last_seen": stamps[-1] if stamps else None,
        # None, not 0, when no opportunity matcher is declared. "0 sessions had an
        # opportunity" is a measurement; "nobody said what an opportunity looks like" is
        # not, and collapsing the two is how a zero comes to read as evidence.
        "opportunity_sessions": len(opportunity_sessions) if opportunity.declared() else None,
        "sessions_with_use_among_opportunity": len(took_it) if opportunity.declared() else None,
        "taken_ratio": (
            round(len(took_it) / len(opportunity_sessions), 3) if opportunity_sessions else None
        ),
        "opportunity_invocations": len(chances_in_window) if opportunity.declared() else None,
        "opportunity_tools": opportunity_tools,
        "per_tool": per_tool,
        "slugs": slugs,
        "exposure": exposure,
    }

    # ------------------------------------------------------------- mechanical checks
    #
    # WHOSE CRITERIA THESE ARE. A [pilot_exit] block survives a demotion on purpose
    # (radar_lib.validate allows it on any entry that WAS a pilot): the criteria were
    # written before the data existed, and deleting them on the way out would let a
    # parked experiment come back with fresh, conveniently looser ones. But surviving is
    # not the same as being under test. Evaluated against the FIRST history entry with
    # ring == pilot whatever the current ring is, the block would keep an entry demoted
    # to observe reporting "pilot review is due" and "min_sessions_with_use NOT met" for
    # an experiment that has already ended. A finding that cannot lead to an action is
    # noise that teaches the reader to skim the findings list.
    px = tool.get("pilot_exit")
    in_pilot = tool.get("ring") == "pilot"
    checks: list[dict] = []
    if px and not in_pilot:
        findings.append(
            f"[NOTE] {name}: [pilot_exit] retained from an earlier pilot and NOT "
            f"evaluated - the entry is at ring={tool.get('ring')!r}. The criteria stay on "
            "the entry as the record of what was promised; they apply again if it is "
            "re-piloted, and re-writing them at that point would be pre-registration "
            "laundering."
        )
    elif px:
        rad = px.get("review_after_days")
        # The LAST pilot entry, not the first: an entry that piloted, was parked and was
        # re-piloted is days into the current experiment, not into the earlier one.
        entered = next(
            (
                h.get("date")
                for h in reversed(tool.get("history") or [])
                if h.get("ring") == "pilot"
            ),
            None,
        )
        if isinstance(rad, int) and entered:
            try:
                age = (dt.date.today() - dt.date.fromisoformat(str(entered))).days
                checks.append(
                    {
                        "check": "review_after_days",
                        "verdict": "DUE" if age >= rad else "not yet",
                        "detail": f"{age}d in pilot since {entered}, review at {rad}d",
                    }
                )
                if age >= rad:
                    findings.append(
                        f"[FLAG] {name}: pilot review is due ({age}d >= {rad}d) - "
                        "a radar session with a human decides the ring, not this script"
                    )
            except ValueError:
                pass
        numeric = {
            "min_sessions_with_use": ("sessions_with_use", "ge"),
            "min_invocations": ("invocations", "ge"),
            "max_error_rate": ("error_rate", "le"),
        }
        for key, (metric, op) in numeric.items():
            if key not in px:
                continue
            want, got = px[key], metrics[metric]
            if got is None:
                verdict, detail = "unevaluated", f"no data for {metric}"
            elif (got >= want) if op == "ge" else (got <= want):
                verdict, detail = "met", f"{metric}={got} vs {key}={want}"
            else:
                verdict, detail = "NOT met", f"{metric}={got} vs {key}={want}"
            checks.append({"check": key, "verdict": verdict, "detail": detail})
            if verdict == "NOT met":
                findings.append(f"[NOTE] {name}: pre-registered {key} not met - {detail}")
    elif in_pilot:
        # Only a pilot owes exit criteria, which is the gate's rule too. Warning on every
        # own/adopt entry printed one line per entry that no action could follow, and
        # buried the warnings that could.
        findings.append(
            f"[WARN] {name}: no [pilot_exit] block - nothing to check the field "
            "data against; criteria written after the data are not criteria"
        )

    # -------------------------------------------------------------------- findings
    if not in_window:
        # THREE READINGS, and the count above tells them apart from none of the others.
        # Naming only two ("not mounted, or the work never called for it") would quietly
        # exclude the third: the tool was there, the work fitted, and the agent never
        # reached for it. A ring is not moved on a zero whose cause is
        # unknown, so the reading the report omits is the reading nobody argues about.
        parts = [
            f"[NOTE] {name}: zero measured use - {len(sessions_in_window)} sessions in "
            "the window, none invoked a matching tool. Not an error: it is the finding. "
            "It has three readings and these counts separate none of them on their own - "
            "(1) the work never called for it, (2) it was not mounted or reachable, "
            "(3) it was there and applicable and was never reached for."
        ]
        # also_runs_in belongs here as much as in the thin-surface branch below, and was
        # consulted only there: an entry that runs entirely inside git hooks or CI reads
        # ZERO here, which is the strongest possible version of the same false conclusion.
        if also_runs_in:
            parts.append(
                "The entry declares surfaces no transcript records - "
                f"{', '.join(also_runs_in)} - so reading (2) is already excluded and the "
                "zero measures reach, not use."
            )
        if opportunity.declared():
            parts.append(
                f"{len(opportunity_sessions)} session(s) had an opportunity by the "
                f"entry's own opportunity matchers, {len(took_it)} took it - so reading "
                "(1) is settled and what remains is (2) against (3)."
                if opportunity_sessions
                else "The entry declares opportunity matchers and 0 session(s) matched "
                "them, which points at reading (1): the occasion never arose."
            )
        findings.append(" ".join(parts))
    else:
        used_frac = len(used_sessions) / max(1, len(sessions_in_window))
        if used_frac < 0.05:
            rate = (
                f"used in {len(used_sessions)}/{len(sessions_in_window)} sessions ({used_frac:.1%})"
            )
            # A FLAG here is false by construction for anything that runs where a
            # transcript cannot see it. A pre-commit hook that fires on every commit
            # still reads as a handful of sessions, because only the agent's own calls
            # are recorded - the number is right and the conclusion drawn from it would
            # be backwards. Where the entry declares the invisible surfaces, the finding
            # says what the count is missing instead of pretending the count is the whole
            # picture.
            if also_runs_in:
                findings.append(
                    f"[NOTE] {name}: {rate}, but this counts only what the AGENT "
                    f"reached for. The entry declares that it also runs in: "
                    f"{', '.join(also_runs_in)} - surfaces no transcript records. Read "
                    "the ratio as reach-frequency, not as adoption."
                )
            else:
                findings.append(
                    f"[FLAG] {name}: thin opportunity surface - {rate}; "
                    "an effect this rare cannot pay for its context cost"
                )
        if metrics["error_rate"] is not None and metrics["error_rate"] > 0.1:
            findings.append(
                f"[WARN] {name}: error rate {metrics['error_rate']:.1%} over "
                f"{len(resolved)} resolved calls"
            )
        if metrics["unresolved"]:
            findings.append(
                f"[NOTE] {name}: {metrics['unresolved']} call(s) have no matching "
                "tool_result in the transcript (interrupted, or the result is in a file "
                "outside the window); their latency is unknown"
            )
    if used_outside_census:
        findings.append(
            f"[NOTE] {name}: {len(used_outside_census)} session(s) with use are not in "
            "the window census - the calls come from sidechain transcripts (subagents, "
            "workflows) whose parent session's own transcript is absent or falls outside "
            "the window. They count in the numerator and deliberately NOT in the "
            "denominator: the denominator is one census shared by every entry, so that a "
            "--all table's rows divide by the same number."
        )
    if malformed:
        findings.append(f"[NOTE] {name}: {malformed} unparseable transcript line(s) skipped")
    if days < 7:
        findings.append(
            f"[WARN] {name}: the window is {days} day{'' if days == 1 else 's'} - "
            "too short for an opportunity-frequency census; widen --since before reading "
            "the sessions-with-use ratio as anything"
        )
    # RETENTION, which is the difference between "nothing happened" and "the evidence is
    # gone". Claude Code prunes transcripts after a configurable retention period, so a
    # window that starts before the oldest surviving transcript has a TRUNCATED
    # denominator and a truncated numerator, and neither is visible in the numbers.
    oldest = index.oldest_record_by_head_scan
    if oldest is not None and oldest > since:
        findings.append(
            f"[WARN] {name}: the census is truncated by retention - the oldest record a "
            f"BOUNDED HEAD SCAN finds on disk is {oldest}, after --since {since}. "
            f"Everything before that was pruned, so both the denominator and the counts "
            f"cover {oldest}..{until}, not the window asked for. The date is a CEILING, "
            "not the edge: only each transcript's first 64 KiB is read, so history "
            "replayed deeper into a resumed session is not seen and the true oldest "
            "record can be earlier."
        )

    # ------------------------------------------------------------------- reconcile
    reconcile: dict | None = None
    if args.reconcile:
        store_raw = ((env or {}).get("paths") or {}).get("transcript_index")
        store = Path(str(store_raw).replace("\\", "/")) if store_raw else None
        loaded = load_transcript_index(store) if store else None
        if store is None:
            findings.append(
                f"[NOTE] {name}: --reconcile asked for, but the {args.env!r} profile "
                "declares no [paths].transcript_index - nothing to cross-check against"
            )
        elif loaded is None:
            findings.append(
                f"[NOTE] {name}: --reconcile asked for, but no derived table at "
                f"{store / 'derived' / 'invocations.jsonl'} - the table has never been "
                "derived here, or the path is wrong"
            )
        else:
            rows, generated_at = loaded
            cutoff = utc_moment(generated_at)
            theirs = index_counts(rows, since, until, globs, skill_globs, command_globs, cutoff)
            ours = our_counts(in_window, command_globs, cutoff)
            if cutoff is not None and cutoff.date() < since:
                findings.append(
                    f"[NOTE] {name}: the invocation table was derived {generated_at}, "
                    f"before the window starts ({since}) - there is nothing to compare "
                    "until it is derived again"
                )
            declared = {
                "command": bool(command_globs),
                "skill": bool(skill_globs),
                "mcp": bool(globs),
            }
            age = derive_age_hours(generated_at)
            kinds = []
            for kind in RECONCILE_KINDS:
                if not declared[kind]:
                    continue
                a, b = ours[kind], theirs[kind]
                rel = abs(a - b) / max(a, b) if max(a, b) else 0.0
                # Every declared kind is compared (see SCRIPT NAMES above
                # RECONCILE_KINDS); `comparable` is part of the report's shape.
                comparable = True
                kinds.append(
                    {
                        "kind": kind,
                        "ours": a,
                        "index": b,
                        "delta": a - b,
                        "relative": round(rel, 4),
                        "comparable": comparable,
                    }
                )
                if comparable and rel > RECONCILE_TOLERANCE:
                    findings.append(
                        f"[WARN] {name}: reconcile drift on `{kind}` - ours {a}, "
                        f"index {b} ({rel:.1%} apart, tolerance "
                        f"{RECONCILE_TOLERANCE:.0%}). Either the two scanners disagree, "
                        f"or the index is stale (derived "
                        f"{generated_at or 'at an unknown time'}"
                        + (f", {age}h ago" if age is not None else "")
                        + ") - check the age before the code."
                    )
            reconcile = {
                "store": str(store),
                "generated_at": generated_at,
                "age_hours": age,
                # `age_hours` is the value to read; `age_days` is derived from it, for a
                # reader who wants the coarser unit without recomputing it.
                "age_days": int(age // 24) if age is not None else None,
                "compared_up_to": generated_at if cutoff is not None else None,
                "tolerance": RECONCILE_TOLERANCE,
                "kinds": kinds,
            }

    doc = {
        "generated_by": "radar field",
        "generated_at": dt.datetime.now(dt.UTC).isoformat(timespec="seconds"),
        "descriptive_only": DESCRIPTIVE_BANNER,
        "tool": name,
        "ring": tool.get("ring"),
        "environment": args.env,
        "claude_home": str(home),
        "match": globs,
        "match_skill": skill_globs,
        "match_command": command_globs,
        "opportunity_match": opportunity.tool,
        "opportunity_match_skill": opportunity.skill,
        "opportunity_match_command": opportunity.command,
        "also_runs_in": also_runs_in,
        "match_override": bool(args.match),
        "window": {
            "since": since.isoformat(),
            "until": until.isoformat(),
            "days": days,
        },
        "scan": {
            "transcripts_on_disk": len(files),
            "in_time_window": n_in_window,
            "prescan_hits": n_prescan,
            "parsed": n_parsed,
            "malformed_lines": malformed,
            "wall_clock_s": wall,
            # The field name carries the caveat because the value cannot: it is the
            # earliest timestamp in any main transcript's first 64 KiB, which is a
            # CEILING on how far back the evidence reaches, not the edge itself.
            "oldest_record_by_head_scan": (
                index.oldest_record_by_head_scan.isoformat()
                if index.oldest_record_by_head_scan
                else None
            ),
        },
        "metrics": metrics,
        "reconcile": reconcile,
        "pilot_exit": px,
        "pilot_exit_evaluated": bool(px) and in_pilot,
        "checks": checks,
        "findings": findings,
        # The raw call list is the audit trail behind the aggregates. It is capped so a
        # busy tool's report stays a document rather than a data dump; the aggregates
        # above are always complete.
        "invocations_recorded": min(len(in_window), RAW_CAP),
        "invocations_truncated": len(in_window) > RAW_CAP,
        "invocations": in_window[:RAW_CAP],
    }

    # Under the data root unless --out-dir names another place. A destination inside the
    # data root, field/ or an --out-dir spelled under it, is written only through
    # write_inside, which refuses a symbolic link on the way.
    data_root = field_dir().parent
    out_dir = (Path(args.out_dir) if args.out_dir else field_dir()) / report_subdir
    inside_root = (
        data_root
        if Path(os.path.abspath(out_dir)).is_relative_to(os.path.abspath(data_root))
        else None
    )
    # A --match run measures something other than what the entry declares, so it must
    # not be able to overwrite the entry's real field record.
    stem = f"{since.isoformat()}_{until.isoformat()}" + ("-probe" if args.match else "")
    md_path, json_path = out_dir / f"{stem}.md", out_dir / f"{stem}.json"
    # field/ is TRACKED, and a session slug is derived from the project path the
    # session ran in - so a report can carry a project's name through its slugs without a
    # word of prose mentioning it. This is post-hoc mining of paths we do not control, so
    # it cannot be fixed at the source: it is mapped out on the way to disk. Only the
    # written artefacts are redacted - `--json` to stdout keeps the real names, because
    # whoever runs it is on the machine that owns them.
    #
    # The same slug carries the home directory, and so do `claude_home` and the index
    # location: every report would name the machine's account. The home goes first, so a
    # scoped term can never split a home path and leave the rest of it behind. The homes
    # declared in `redact.local.toml` go with it: sessions synced from another machine
    # keep that machine's slugs, and this is the one writer that meets them.
    _terms, _homes = scoped_terms(), [home_dir(), *extra_homes()]

    def _redact(text: str) -> str:
        return redact_text(redact_homes(text, _homes), _terms)

    # The Markdown escapes transcript-derived values (a backslash is doubled, a tag's
    # brackets become entities), and a home or a scoped term spelled inside an escaped
    # value would no longer match its redaction pattern. So the values are redacted
    # first, through their JSON spelling, and the rendered text once more.
    shown = json.loads(_redact(json.dumps(doc)))
    # LF on every OS, like every tracked file the engine writes: CRLF would show each
    # report as modified on Windows until it is staged.
    written = {
        md_path: _redact(render_md(shown)),
        json_path: _redact(json.dumps(doc, indent=2) + "\n"),
    }
    if inside_root is not None:
        # Both files are judged before either is written, so a refusal leaves no half.
        refused = [e for e in (write_error(inside_root, p) for p in written) if e]
        if refused:
            for err in refused:
                print(f"[FAIL] {name}: {err} - the report was not written")
            raise SystemExit(1)
    for path, text in written.items():
        if inside_root is None:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
        else:
            write_inside(inside_root, path, text)
    doc["_paths"] = {"md": str(md_path), "json": str(json_path)}
    doc["_scan_line"] = (
        f"scanned {n_parsed}/{n_in_window} of {len(files)} transcripts in {wall}s "
        f"({DESCRIPTIVE_BANNER.split(' - ')[0]})"
    )
    return doc


def print_report(doc: dict) -> None:
    """The single-tool console read-out."""
    m, w = doc["metrics"], doc["window"]
    for f in doc["findings"]:
        print(f)
    print(
        f"\n{doc['tool']}: {m['invocations']} invocations, "
        f"{m['sessions_with_use']}/{m['sessions_in_window']} sessions with use, "
        f"{len(m['per_tool'])} distinct tools, window {w['since']}..{w['until']}"
    )
    print(doc["_scan_line"])
    for line in reconcile_lines(doc["tool"], doc.get("reconcile")):
        print(line)
    print(f"wrote {doc['_paths']['md']}")
    print(f"wrote {doc['_paths']['json']}")


# ONE LINE FOR A SCHEDULED REVIEW. Running one tool at a time is how a declared matcher
# goes a month without ever being run, and a matcher that is never run is not a deferred
# measurement - the transcripts it needed get pruned. --all makes the whole board one
# command.
INACTIVE_RINGS = ("observe", "discard")
SUMMARY_HEADER = ("tool", "ring", "inv", "sessions", "err", "findings")


def selected_tools(tools: list[dict], include_inactive: bool) -> list[dict]:
    """Entries with a declared matcher, in name order. Inactive rings dropped by default.

    An observe/discard entry claims nothing, so there is nothing about it to check - and
    running the lot on every scheduled review would bury the entries whose rings ARE
    claims. Pass --include-inactive when the question is about a demoted entry
    specifically.
    """
    out = []
    for t in sorted(tools, key=lambda t: str(t.get("name") or "")):
        tel = t.get("telemetry") or {}
        if not any(tel.get(k) for k in MATCHER_KEYS):
            continue
        if not include_inactive and t.get("ring") in INACTIVE_RINGS:
            continue
        out.append(t)
    return out


def summary_table(rows: list[list[str]]) -> list[str]:
    widths = [max(len(str(r[i])) for r in [list(SUMMARY_HEADER), *rows]) for i in range(6)]
    fmt = "  ".join(f"{{:<{w}}}" for w in widths)
    out = [fmt.format(*SUMMARY_HEADER), fmt.format(*("-" * w for w in widths))]
    out += [fmt.format(*r) for r in rows]
    return out


@reports_profile_errors
def main() -> None:
    args = build_parser().parse_args()
    # The banner goes to stderr, which is what keeps `--json` a parseable document.
    root = begin_command(args.data_root)
    args.env = args.env or default_environment(root)
    if bool(args.tool) == bool(args.all):
        print("[FAIL] name one tool, or pass --all - not both, not neither")
        sys.exit(2)
    if args.all and args.json:
        # There is no defined single document for one report per entry, and silently
        # ignoring the flag would hand a script an empty parse instead of an error.
        # Each entry's JSON is on disk under field/<tool>/ either way.
        print("[FAIL] --json reports one tool; with --all, read field/<tool>/*.json")
        sys.exit(2)

    tools = load_tools()
    env = load_environment(args.env)
    if env is None and not args.claude_home:
        print(f"[FAIL] no environment named {args.env!r} and no --claude-home")
        sys.exit(1)
    home = Path(args.claude_home or (env or {}).get("paths", {}).get("claude_home", ""))
    projects = home / "projects"
    if not projects.is_dir():
        print(f"[FAIL] no transcript directory at {projects}")
        sys.exit(1)
    files = discover(projects)
    index_cache: dict = {}

    if not args.all:
        tool = next((t for t in tools if t.get("name") == args.tool), None)
        if tool is None:
            print(f"[FAIL] {args.tool}: no tools/*.toml entry with this name")
            sys.exit(1)
        doc = run_tool(tool, args, env, home, files, index_cache)
        if doc is None:
            sys.exit(1)
        if args.json:
            print(json.dumps({k: v for k, v in doc.items() if not k.startswith("_")}, indent=2))
        else:
            print_report(doc)
        sys.exit(1 if any(f.startswith("[FAIL]") for f in doc["findings"]) else 0)

    selected = selected_tools(tools, args.include_inactive)
    if not selected:
        print("[FAIL] --all selected no entry - does any tools/*.toml declare a matcher?")
        sys.exit(1)
    rows: list[list[str]] = []
    fails = 0
    for tool in selected:
        doc = run_tool(tool, args, env, home, files, index_cache)
        if doc is None:
            fails += 1
            rows.append([str(tool.get("name")), str(tool.get("ring")), "-", "-", "-", "FAIL"])
            continue
        m = doc["metrics"]
        for f in doc["findings"]:
            print(f)
        for line in reconcile_lines(doc["tool"], doc.get("reconcile")):
            print(line)
        fails += sum(1 for f in doc["findings"] if f.startswith("[FAIL]"))
        rows.append(
            [
                doc["tool"],
                str(doc["ring"]),
                str(m["invocations"]),
                f"{m['sessions_with_use']}/{m['sessions_in_window']}",
                str(m["errors"]),
                str(len(doc["findings"])),
            ]
        )
    print()
    for line in summary_table(rows):
        print(line)
    # Without --since each entry uses its own [telemetry].since, so there is no single
    # window to name and claiming one would be the kind of tidy lie this script exists
    # to remove.
    window = (
        f"{args.since}..{args.until or dt.datetime.now(dt.UTC).date()}"
        if args.since
        else "per-entry [telemetry].since"
    )
    print(
        f"\n{len(selected)} entr{'y' if len(selected) == 1 else 'ies'} with a matcher, "
        f"window {window} - {fails} FAIL"
    )
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
